version: 2

models:
  - name: fact_trips
    description: "Fact table containing taxi trips with a generated surrogate trip_id"
    columns:
      - name: trip_id
        description: "Surrogate primary key for each trip"
        tests:
          - not_null
          - unique

      - name: vendor_id
        description: "Taxi vendor identifier"
        tests:
          - not_null

      - name: pickup_datetime
        description: "Datetime when the trip started"
        tests:
          - not_null

      - name: dropoff_datetime
        description: "Datetime when the trip ended"
        tests:
          - not_null

      - name: pickup_location_id
        description: "Pickup taxi zone location ID"
        tests:
          - not_null

      - name: dropoff_location_id
        description: "Dropoff taxi zone location ID"
        tests:
          - not_null

      - name: fare_amount
        description: "Fare amount for the trip"

      - name: total_amount
        description: "Total charged amount including all fees"
