name: 'ny_taxi_dbt'

# This setting configures which "profile" dbt uses for this project.
profile: 'ny_taxi_dbt'

config-version: 2

source-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  models:
  ny_taxi_dbt:
    staging:
      +schema: staging
      +materialized: view

    analytics:
      +schema: analytics
      +materialized: table

